# Generated by Django 5.0.7 on 2024-07-31 02:08

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('admin_fname', models.CharField(max_length=30)),
                ('admin_lname', models.CharField(max_length=30)),
                ('admin_email', models.EmailField(max_length=255, unique=True)),
                ('admin_dept', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('admin_password', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_sci_100l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_num', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('CSC_101', models.IntegerField(default=0)),
                ('CSC_102', models.IntegerField(default=0)),
                ('CSC_105', models.IntegerField(default=0)),
                ('CSC_111', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=100)),
                ('week', models.IntegerField(default=1)),
                ('total_attendance_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10)),
                ('machine_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('matric_number', models.CharField(max_length=10)),
            ],
            managers=[
                ('machine', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_dept', models.CharField(max_length=50)),
                ('student_course', models.CharField(max_length=10)),
                ('student_address', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
            ],
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student_comp_sci_100L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('matric_num', models.CharField(max_length=20, unique=True)),
                ('CSC_101', models.IntegerField(default=0)),
                ('CSC_102', models.IntegerField(default=0)),
                ('CSC_105', models.IntegerField(default=0)),
                ('CSC_111', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=100)),
                ('week', models.IntegerField(default=1)),
                ('total_attendance_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dept', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('course_lecturer', models.CharField(max_length=50)),
                ('matric_number', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('attendance_score', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.student')),
            ],
            managers=[
                ('attendance_report', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.student')),
            ],
            managers=[
                ('attendance', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('course', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('course_lecturer', models.CharField(max_length=50)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.machine')),
            ],
            managers=[
                ('timetable', django.db.models.manager.Manager()),
            ],
        ),
    ]
