# Generated by Django 5.0.7 on 2024-09-22 09:25
from datetime import timezone, date

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


today = date.today()
today.strftime("%d/%m/%Y")
today_format = today.strftime("%d/%m/%Y")

class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0002_comp_sci_200l_comp_sci_300l_comp_sci_400l_econ_100l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law_100l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_num', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('LAW_101', models.IntegerField(default=0)),
                ('LAW_102', models.IntegerField(default=0)),
                ('LAW_103', models.IntegerField(default=0)),
                ('LAW_104', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=100)),
                ('week', models.IntegerField(default=1)),
                ('total_attendance_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Law_200l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mateic_num', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('LAW_201', models.IntegerField(default=0)),
                ('LAW_202', models.IntegerField(default=0)),
                ('LAW_203', models.IntegerField(default=0)),
                ('LAW_204', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=200)),
                ('week', models.IntegerField(default=1)),
                ('total_attendance_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Law_300l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_num', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('LAW_301', models.IntegerField(default=0)),
                ('LAW_302', models.IntegerField(default=0)),
                ('LAW_303', models.IntegerField(default=0)),
                ('LAW_304', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=300)),
                ('week', models.IntegerField(default=1)),
                ('total_attendance_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Law_400l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_num', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('LAW_401', models.IntegerField(default=0)),
                ('LAW_402', models.IntegerField(default=0)),
                ('LAW_403', models.IntegerField(default=0)),
                ('LAW_404', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_dept', models.CharField(max_length=50)),
                ('total_attendance_score', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_name', models.CharField(max_length=50)),
                ('seminar_venue', models.CharField(max_length=50)),
                ('seminar_date', models.DateField()),
                ('seminar_time', models.TimeField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.staff')),
            ],
            managers=[
                ('seminar', django.db.models.manager.Manager()),
            ],
        ),

        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retreat_name', models.CharField(max_length=50)),
                ('retreat_venue', models.CharField(max_length=50)),
                ('retreat_date', models.DateField()),
                ('retreat_time', models.TimeField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.staff')),
            ],
            managers=[
                ('retreat', django.db.models.manager.Manager()),
            ],
        ),

        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=50)),
                ('training_venue', models.CharField(max_length=50)),
                ('training_date', models.DateField()),
                ('training_time', models.TimeField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.staff')),
            ],
            managers=[
                ('training', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=50)),
                ('workshop_venue', models.CharField(max_length=50)),
                ('workshop_date', models.DateField()),
                ('workshop_time', models.TimeField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_proj.staff')),
            ],
            managers=[
                ('workshop', django.db.models.manager.Manager()),
            ],
        ),
    ]
