# Generated by Django 5.0.7 on 2024-09-22 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0005_staff_conference_machine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(17, 25, 41, 22925)),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='machine_id',
            field=models.CharField(max_length=50),
        ),
    ]
