# Generated by Django 5.0.7 on 2024-09-22 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0006_alter_staff_conference_conference_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_category',
            field=models.CharField(default='category', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(17, 35, 23, 219164)),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_title',
            field=models.CharField(default='conference', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_type',
            field=models.CharField(default='type conf', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_venue',
            field=models.CharField(default='venue', max_length=50),
        ),
    ]
