# Generated by Django 5.0.7 on 2024-09-22 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0007_alter_staff_conference_conference_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(17, 47, 49, 710085)),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
