# Generated by Django 5.1.7 on 2025-03-13 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0008_alter_staff_conference_conference_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(1, 6, 40, 612396)),
        ),
    ]
