# Generated by Django 5.1.7 on 2025-03-22 13:17

import datetime
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0009_alter_staff_conference_conference_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
            managers=[
                ('event', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VUA_100l_mass_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_fname', models.CharField(max_length=50)),
                ('student_mname', models.CharField(max_length=50)),
                ('student_lname', models.CharField(max_length=50)),
                ('student_matric_no', models.CharField(max_length=20)),
                ('student_level', models.IntegerField(default=100)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('week_1', models.IntegerField(default=0)),
                ('week_2', models.IntegerField(default=0)),
                ('week_3', models.IntegerField(default=0)),
                ('week_4', models.IntegerField(default=0)),
                ('week_5', models.IntegerField(default=0)),
                ('week_6', models.IntegerField(default=0)),
                ('week_7', models.IntegerField(default=0)),
                ('week_8', models.IntegerField(default=0)),
                ('week_9', models.IntegerField(default=0)),
                ('week_10', models.IntegerField(default=0)),
                ('week_11', models.IntegerField(default=0)),
                ('week_12', models.IntegerField(default=0)),
                ('student_total_attendance_score', models.IntegerField(default=0)),
                ('student_remarks', models.CharField(max_length=100)),
            ],
            managers=[
                ('student_event', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(13, 17, 50, 631853)),
        ),
    ]
