# Generated by Django 5.1.7 on 2025-03-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0010_student_event_vua_100l_mass_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vua_100l_mass_students',
            name='student_gender',
            field=models.CharField(default='not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(15, 3, 59, 256445)),
        ),
    ]
