# Generated by Django 5.1.7 on 2025-03-23 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0014_alter_staff_conference_conference_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vua_100l_mass_students',
            name='student_mname',
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(5, 46, 19, 836952)),
        ),
    ]
