# Generated by Django 5.1.7 on 2025-03-23 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0015_remove_vua_100l_mass_students_student_mname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vua_100l_mass_students',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(7, 45, 59, 74661)),
        ),
        migrations.AlterField(
            model_name='vua_100l_mass_students',
            name='student_matric_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
