# Generated by Django 5.1.7 on 2025-03-26 03:34

import datetime
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0017_vua_200l_mass_students_vua_300l_mass_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_mass_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('staff_fname', models.CharField(max_length=50)),
                ('staff_lname', models.CharField(max_length=50)),
                ('staff_gender', models.CharField(default='not specified', max_length=20)),
                ('staff_title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('staff_category', models.CharField(max_length=50)),
                ('week_1_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_2_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_3_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_4_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_5_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_6_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_7_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_8_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_9_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_10_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_11_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_12_clockin_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('staff_total_attendance_score', models.IntegerField(default=0)),
                ('staff_remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            managers=[
                ('staff_event', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(3, 34, 37, 546298)),
        ),
    ]
