# Generated by Django 5.1.7 on 2025-03-26 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0018_staff_mass_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(3, 44, 9, 263039)),
        ),
    ]
