# Generated by Django 5.1.7 on 2025-03-26 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0019_alter_staff_conference_conference_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(6, 35, 11, 383188)),
        ),
    ]
