# Generated by Django 5.1.7 on 2025-03-27 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0020_alter_staff_conference_conference_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_10_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_11_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_12_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_1_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_2_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_3_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_4_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_5_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_6_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_7_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_8_clockin_time',
        ),
        migrations.RemoveField(
            model_name='staff_mass_records',
            name='week_9_clockin_time',
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff_mass_records',
            name='week_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=datetime.time(5, 41, 43, 671955)),
        ),
    ]
