# Generated by Django 5.1.7 on 2025-09-24 09:01

import attendance_proj.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0021_remove_staff_mass_records_week_10_clockin_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_dept', models.CharField(max_length=100)),
                ('conference_title', models.CharField(default='conference', max_length=200)),
                ('conference_venue', models.CharField(default='venue', max_length=200)),
                ('conference_date', models.DateField(default=django.utils.timezone.now)),
                ('conference_time', models.TimeField(default=attendance_proj.models.get_current_time)),
                ('conference_type', models.CharField(default='type conf', max_length=100)),
                ('conference_category', models.CharField(default='category', max_length=100)),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attendance_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Staff Conference',
                'verbose_name_plural': 'Staff Conferences',
                'db_table': 'attendance_proj_staff_conference',
            },
        ),
        migrations.DeleteModel(
            name='staff_Conference',
        ),
    ]
