# Generated by Django 5.1.7 on 2025-09-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0022_staffconference_delete_staff_conference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffconference',
            options={'managed': False, 'verbose_name': 'Staff Conference', 'verbose_name_plural': 'Staff Conferences'},
        ),
    ]
