# Generated by Django 5.1.7 on 2025-09-24 09:13

import datetime
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0023_alter_staffconference_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_dept', models.CharField(max_length=100)),
                ('conference_title', models.CharField(default='conference', max_length=500)),
                ('conference_venue', models.CharField(default='venue', max_length=500)),
                ('conference_date', models.DateField(default=django.utils.timezone.now)),
                ('conference_time', models.TimeField(default=datetime.time(9, 13, 6, 196722))),
                ('conference_type', models.CharField(default='type conf', max_length=100)),
                ('conference_category', models.CharField(default='category', max_length=200)),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('remarks', models.CharField(max_length=100)),
                ('attendance_score', models.IntegerField(default=0)),
            ],
            managers=[
                ('conference', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='StaffConference',
        ),
    ]
