# Generated by Django 5.1.7 on 2025-09-24 12:05

import attendance_proj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0024_staff_conference_delete_staffconference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_conference',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='staff_conference',
            name='clock_out',
        ),
        migrations.AddField(
            model_name='staff_conference',
            name='staff_faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_conference',
            name='staff_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='conference_time',
            field=models.TimeField(default=attendance_proj.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='machine_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_conference',
            name='remarks',
            field=models.CharField(default='Not Marked', max_length=100),
        ),
    ]
