# Generated by Django 5.1.7 on 2025-09-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0025_remove_staff_conference_clock_in_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff_conference',
            managers=[
            ],
        ),
    ]
