# Generated by Django 5.1.7 on 2025-09-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0026_alter_staff_conference_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_conference',
            name='staff_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_conference',
            name='staff_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
