# Generated by Django 5.1.7 on 2026-01-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0027_staff_conference_staff_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_conference',
            name='staff_rfid',
            field=models.CharField(blank=True, help_text='Staff RFID card number', max_length=50, null=True, unique=True),
        ),
    ]
