# Generated by Django 5.1.7 on 2026-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_proj', '0028_staff_conference_staff_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_mass_records',
            name='staff_rfid',
            field=models.CharField(blank=True, help_text='Staff RFID card number', max_length=50, null=True, unique=True),
        ),
    ]
